services:
  - type: web
    name: relay-release-management
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RELAY_ACCESS_KEY
        generateValue: true
      - key: RELAY_DATA_DIR
        value: /data
    disk:
      name: relay-data
      mountPath: /data
      sizeGB: 1
